[font]
size = 11.0

[font.bold]
family = "terminus"
style = "Bold"

[font.bold_italic]
family = "terminus"
style = "Bold Italic"

[font.normal]
family = "terminus"
style = "Regular"

[window]
opacity = 0.8
